colors = ['red','yellow','orange','green','blue','purple','white','brown','chartreuse']
print('I have',len(colors), 'colors')
print(colors[0])
print(colors[1])
print(colors[2])
print(colors[3])
print(colors[4])
print(colors[5])
print(colors[6])
print(colors[7])
print(colors[8])